name: Echo Social Network

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      max-parallel: 4
      matrix:
        python-version: ['3.12']

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Dependencies, VENV, Make Django Migrations
      run: |
        appfile=$(find ~/echo-runner -type f -name "*manage.py")
        appdir=$(dirname $appfile)
        cd $appdir
        echo "${{ secrets.ECHO_ENV }}" > echo/.env
        python3 -m venv echo-env
        source echo-env/bin/activate
        pip install -r requirements.txt
        pip install gunicorn psycopg2-binary
        python manage.py makemigrations users
        python manage.py makemigrations posts
        python manage.py makemigrations news
        python manage.py makemigrations chat
        python manage.py makemigrations notifications
        python manage.py makemigrations
        python manage.py migrate
        python manage.py collectstatic --noinput

    - name: Run Tests
      run: |
        envfile=$(find ~/echo-runner -type f -wholename "*echo-env/bin/activate")
        source $envfile
        python manage.py test
